name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-api-gateway:
    name: Build & Test API Gateway
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build
        working-directory: ./api-gateway
        run: |
          go mod tidy
          go build -v ./...

      - name: Run tests
        working-directory: ./api-gateway
        run: |
          go test -v ./...

      - name: Code coverage
        working-directory: ./api-gateway
        run: |
          go test -cover ./...
